ARG VERSION=v3.2.1

FROM prom/prometheus:${VERSION}

# Install envsubst (part of gettext)
USER root
RUN apk add --no-cache gettext

# Copy the prom.yml template
COPY prom.yml /etc/prometheus/prom.yml.template

# Create entrypoint script that substitutes env vars
RUN echo '#!/bin/sh' > /docker-entrypoint.sh && \
    echo 'envsubst < /etc/prometheus/prom.yml.template > /etc/prometheus/prom.yml' >> /docker-entrypoint.sh && \
    echo 'exec /bin/prometheus "$@"' >> /docker-entrypoint.sh && \
    chmod +x /docker-entrypoint.sh

# Switch back to prometheus user
USER nobody

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["--config.file=/etc/prometheus/prom.yml", "--storage.tsdb.path=/prometheus"]
